### ISSUE TITLE
Feature request: Remove entry "modules" in function "install_import _hook()"

### ISSUE THREAD

**Issue by im-Kitsch** [google/jaxtyping#101]
Hi, 

this would be a "nitpicking" feature request, but I think it would be very helpful: currently if we use a context manager `with install_import_hook()`, e.g.: 

```
with install_import_hook("foo", "typeguard.typechecked"):
    import foo          # Any module imported inside this `with` block, whose
    import foo.bar      # name begins with the specified string, will
    import foo.bar.qux  # automatically have both `@jaxtyped` and the specified
                        # typechecker applied to all of their functions.
```

but actually, for `with ...("foo", ...)` and `import foo`, 'foo' is repeated and redundant,  and new user would be confused for this repeating. It would be more natural to just do with and automatically decorate all imported functions and classes, it would be more intuitive. 

```
with install_import_hook("typeguard.typechecked"):
    import foo          
    import bar
    import foob
```

Or maybe `modules` could be a optionall parameter for all imported packages, functions could be like :  `install_import_hook("typeguard.typechecked", modules=None)`

thanks for your great works.

**Comment by patrick-kidger** [comment]
The reason for this is because `import foo` may, as part of the import process, transitively import other libraries. And we need to know whether or not to run the hook on those as well. E.g. if `foo/__init__.py` looks like:
```python
import foo.bar as bar
import scipy
...
```
then you probably do want to hook `import foo.bar` (and cannot wait until you later import it yourself -- by then its too late), but you probably don't want to hook `scipy`!

**Comment by im-Kitsch** [comment]
Oh, I see, thanks, then I think this could be closed
