### ISSUE TITLE
Type annotations must now include an explicit array type

### ISSUE THREAD

**Issue by neel04** [google/jaxtyping#106]
Apparently, if we don't specify the shape - then we trigger this error?

```py
ValueError: As of jaxtyping v0.2.0, type annotations must now include an explicit array type. For example `jaxtyping.Float32[jax.Array, 'foo bar']`.
```

Why is shape required - when the error clearly talks about an "explicit array type"?
Any way I can remove this behavior?

---

Repro, if needed for some reason:

```py
In [1]: from jaxtyping import Array, Float32

In [2]: import jax.numpy as jnp

In [3]: def test() -> Float32[Array]:
   ...:     return jnp.ones(64,)
   ...: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 def test() -> Float32[Array]:
      2     return jnp.ones(64,)

File ~/miniconda3/envs/react_jax/lib/python3.10/site-packages/jaxtyping/_array_types.py:523, in _MetaAbstractDtype.__getitem__(cls, item)
    521 def __getitem__(cls, item: tuple[Any, str]):
    522     if not isinstance(item, tuple) or len(item) != 2:
--> 523         raise ValueError(
    524             "As of jaxtyping v0.2.0, type annotations must now include an explicit "
    525             "array type. For example `jaxtyping.Float32[jax.Array, 'foo bar']`."
    526         )
    527     array_type, dim_str = item
    528     del item

ValueError: As of jaxtyping v0.2.0, type annotations must now include an explicit array type. For example `jaxtyping.Float32[jax.Array, 'foo bar']`.

In [4]: def test() -> Float32[Array, 'length']:
   ...:     return jnp.ones(64,)
   ...:
   
In [5]: a = test(); print(a)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
```

**Comment by patrick-kidger** [comment]
This error message reflects the fact that way back when jaxtyping was first released, it supported syntax of the form `Float["some shape"]`. In practice that turned out to be incompatible with static type checkers, which is why things changed to demand the inclusion of an array time.

I'll grant you that the error message isn't terribly informative if you do `Float[Array]` instead though. I'd be happy to take a PR adjust this to mention that both an array type and a shape must be included.

In your case, if you want to specify just the dtype but not the shape, then you can do this with `Float[Array, "..."]`.

**Comment by neel04** [comment]
That's dope 🔥 cheers

**Comment by neel04** [comment]
https://github.com/google/jaxtyping/blob/e347c480d51b2cf0671470b522ba09e38a0e9e25/jaxtyping/_array_types.py#L524

That's the only change to make, yeah?

**Comment by patrick-kidger** [comment]
Yup!

**Comment by neel04** [comment]
PR-ed! closing convo here :)
