### ISSUE TITLE
Would/should `isinstance(x,i)` make sense for scalars?

### ISSUE THREAD

**Issue by awf** [google/jaxtyping#12]
I might want to write
```python
@jax.jit
@jaxtyped
def foo1(x: int, t: f32["N"]):
    y: int = x + 3
    assert isinstance(y, int), f"y is a {type(y)}!"
    ...
```
But that won't work with JIT:
```
AssertionError: y is a <class 'jax.interpreters.partial_eval.DynamicJaxprTracer'>!
```

I thought "Aha! I'll just use a `jaxtyping.i`, that will understand the situation"
```python
@jax.jit
@jaxtyped
def foo1(x: int, t: f32["N"]):
    y: int = x + 3
    assert isinstance(y, jaxtyping.i), f"y is a {type(y)}!"
    ...
```
But that says
```
RuntimeError: Do not use `isinstance(x, jaxtyping.i`. If you want to check just the dtype of an array, then use `jaxtyping.i["..."]`.
```

> Is there a way to get this check aware of tracers?

[Edit: Doh, I see that `i[""]` passes the check.  It feels a little verbose, but works fine.]

**Comment by patrick-kidger** [comment]
FWIW I've contemplated adding e.g. `Scalar = Array[""]` into jaxtyping as a convenience. The only reason I haven't is because I'd need to think about the neatest syntax for distinguishing integer vs float etc., and moreover because we might wish to consider defining something equivalent to e.g. `Union[int, i[""]]` which handles the Python builtin `int`/`float`/`bool`/`complex` as well.
