### ISSUE TITLE
Using `jaxtyping` with torch

### ISSUE THREAD

**Issue by brentyi** [google/jaxtyping#18]
Hi,

First off, thanks for the great library!

I'm really interested in  using `jaxtyping`-style syntax with torch, and was wondering:
- Are there any plans to backport the recent syntax changes to `torchtyping`?
    - `torchtyping` is great as-is, but I've been holding off on using it various projects because of incompatibility with static checkers. The recent shift to the `typing.Annotated`-style syntax seems to fix that.
- And if not, would it be possible to release `jaxtyping` without a depedency on `jax`? It seems like it supports torch pretty well already, I'd just prefer to not ship torch projects with a jax dependency.

Thanks again!!

**Comment by patrick-kidger** [comment]
Hey there! Yep, I'd love to update torchtyping as well.

I'm planning to essentially:
- copy-paste the jaxtyping codebase
- remove the JAX parts (e.g. PyTrees)
- Add a backward-compatible new version of `torchtyping.TensorType` that internally lowers to produce the new thing.
- Update all the documentation, tests, etc.

In practice that's a fair amount of work so it's not a priority for me right now.

If this is important to you then I'd welcome a PR against torchtyping that does the above.

**Comment by brentyi** [comment]
Makes sense, thanks for the fast reponse!

Have you toyed with the possibility of merging the projects?

I'm happy to carve out time for a PR, but the duplication is mildly uncomfortable. `torch` will apparently also have PyTrees soon so fully removing that may not even be desired: https://github.com/pytorch/pytorch/issues/65761

I could also see myself using this kind of thing for projects with just vanilla Numpy. :slightly_smiling_face:

**Comment by patrick-kidger** [comment]
Yep, I did consider merging things. This ends up being infeasible due to edge cases, e.g. JAX and PyTorch (eventually) having different PyTree manipulation routines.

Anyway, great - go ahead and open a PR on torchtyping whenever you like. (And for now I'm happy to cut out PyTrees since PyTorch doesn't support these yet; easy enough to add back later.)

**Comment by patrick-kidger** [comment]
1. I suspect at a technical level this might be feasible. (PyTrees and dtypes are the main two discrepancies.) The dominant issues here are:

    - Time: supporting more things takes up dev time and maintenance time. In particular thinking hard about how you achieve compatibility. I'm not a current PyTorch user, and jaxtyping isn't my day job -- just a side-project (one of many I support).
    - Marketability: "jaxtyping" is a much easier thing to advertise than a generic `arraytyping` library!
    - Simplicity: it's important both to me as a dev, and to new users looking to understand the API, that we don't have too many special cases squirrelled away.
    - Feature creep: once we have `.jax` and `.torch` namespaces then before long someone will ask me to support another library I don't currently use ;)
    
   (Besides which I think the name `arraytyping` would need to be revisited given the presence of PyTrees in the library!)

2. Yup, this was considered. At the moment so far as static type checking is concerned, our `Float32` is actually a `typing.Annotated`, so that `Float32[Array, "foo bar"]` is treated as `Annotated[Array, "foo bar"]` and thus treated as just `Array`. If we were to go for an `Array[Float32, "foo bar"]` syntax then we'd be setting `Array = Annotated`, and then that would break whenever someone just writes `def foo(x: Array)`.

**Comment by brentyi** [comment]
Thanks for the detailed explanation! That's convincing on both fronts; on (2) it seems like removing `Array = Annotated` and just using `Shaped = Annotated` with `Float32 = Annotated[jnp.ndarray, "some_float32_marker"]` would result in a sensible API (eg `func(shaped_array: Shaped[Float32, "c h w"], unshaped_array: Float32)`), but the distinction is minor and there are cons to that approach too.

Will do my best to make a PR (probably at the end of) this week!
